services:
  - type: web
    name: hydronyx-backend
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install geopandas && pip install -r requirements.txt"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
